/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix
{
    using Fastpix.Hooks;
    using Fastpix.Models.Components;
    using Fastpix.Models.Errors;
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    using Fastpix.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading;
    using System.Threading.Tasks;

    public interface IInVideoAI
    {

        /// <summary>
        /// Generate video chapters
        /// 
        /// <remarks>
        /// This endpoint enables you to generate chapters for an existing media file.<br/>
        /// <br/>
        /// #### How it works<br/>
        /// 1. Make a `PATCH` request to this endpoint, replacing `&lt;mediaId&gt;` with the ID of the media for which you want to generate chapters.<br/>
        /// 2. Include the `chapters` parameter in the request body to enable.<br/>
        /// 3. The response contains the updated media data, confirming the changes made.<br/>
        /// <br/>
        /// You can use the &lt;a href=&quot;https://fastpix.com/docs/ai-events/in-video-ai-events#videomediaaichaptersready&quot;&gt;video.mediaAI.chapters.ready&lt;/a&gt; webhook event to track and notify about the chapters generation.<br/>
        /// <br/>
        /// **Use case:** This is particularly useful when a user uploads a video and later decides to enable chapters without re-uploading the entire video.<br/>
        /// <br/>
        /// Related guide: &lt;a href=&quot;https://fastpix.com/docs/video-intelligence/generate-video-chapters&quot;&gt;Video chapters&lt;/a&gt;<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<UpdateMediaChaptersResponse> UpdateMediaChaptersAsync(string mediaId, UpdateMediaChaptersRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);

        /// <summary>
        /// Generate named entities
        /// 
        /// <remarks>
        /// This endpoint allows you to extract named entities from an existing media.<br/>
        /// Named Entity Recognition (NER) is a fundamental natural language processing (NLP) technique that identifies and classifies key information (entities) in text into predefined categories. For instance:<br/>
        /// <br/>
        ///   - Organizations (for example, &quot;Microsoft&quot;, &quot;United Nations&quot;)<br/>
        ///   - Locations (for example, &quot;Paris&quot;, &quot;Mount Everest&quot;)<br/>
        ///   - Product names (for example, &quot;iPhone&quot;, &quot;Coca-Cola&quot;)<br/>
        /// <br/>
        /// #### How it works<br/>
        /// 1. Make a PATCH request to this endpoint, replacing `&lt;mediaId&gt;` with the ID of the media you want to extract named-entities.<br/>
        /// 2. Include the `namedEntities` parameter in the request body to enable.<br/>
        /// 3. Receive a response containing the updated media data, confirming the changes made.<br/>
        /// <br/>
        /// You can use the &lt;a href=&quot;https://fastpix.com/docs/ai-events/in-video-ai-events#videomediaainamedentitiesready&quot;&gt;video.mediaAI.named-entities.ready&lt;/a&gt; webhook event to track and notify about the named entities extraction.<br/>
        /// <br/>
        /// **Use case:** If a user uploads a video and later decides to enable named entity extraction without re-uploading the entire video.<br/>
        /// <br/>
        /// Related guide: &lt;a href=&quot;https://fastpix.com/docs/video-intelligence/extract-named-entities-from-a-video&quot;&gt;Named entities&lt;/a&gt;<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<UpdateMediaNamedEntitiesResponse> UpdateNamedEntitiesAsync(string mediaId, UpdateMediaNamedEntitiesRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);
    }

    public class InVideoAI: IInVideoAI
    {
        public SdkConfig SDKConfiguration { get; private set; }

        private const string ContentTypeJson = "application/json";
        private const string UnknownContentTypeMessage = "Unknown content type received";
        private const string ApiErrorMessage = "API error occurred";

        public InVideoAI(SdkConfig config)
        {
            SDKConfiguration = config;
        }

        private static RetryConfig BuildDefaultRetryConfig()
        {
            var backoff = new BackoffStrategy(
                initialIntervalMs: 1000L,
                maxIntervalMs: 10000L,
                maxElapsedTimeMs: 3600000L,
                exponent: 1.5
            );
            return new RetryConfig(
                strategy: RetryConfig.RetryStrategy.BACKOFF,
                backoff: backoff,
                retryConnectionErrors: true
            );
        }

        private async Task<HttpResponseMessage> SendWithHooksAsync(Fastpix.Utils.Retries.Retries retries, HookContext hookCtx)
        {
            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int statusCode = (int)httpResponse.StatusCode;

                if (statusCode >= 400 && statusCode < 600)
                {
                    var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (hooked != null)
                    {
                        httpResponse = hooked;
                    }
                }
            }
            catch (Exception error)
            {
                var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (hooked == null)
                {
                    throw;
                }
                httpResponse = hooked;
            }

            return await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);
        }

        private static T DeserializeOrThrow<T>(string body, HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, NullValueHandling nullValueHandling, string typeName)
        {
            try
            {
                return ResponseBodyDeserializer.DeserializeNotNull<T>(body, nullValueHandling);
            }
            catch (Exception ex)
            {
                throw new ResponseValidationException($"Failed to deserialize response body into {typeName}.", httpRequest, httpResponse, body, ex);
            }
        }

        public async Task<UpdateMediaChaptersResponse> UpdateMediaChaptersAsync(string mediaId, UpdateMediaChaptersRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new UpdateMediaChaptersRequest()
            {
                MediaId = mediaId,
                Body = body,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/on-demand/{mediaId}/chapters", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Patch, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "update-media-chapters", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if (responseStatusCode == 200)
            {
                if (Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<UpdateMediaChaptersResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "UpdateMediaChaptersResponseBody");

                    return new UpdateMediaChaptersResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Object = obj
                    };
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            if (responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            if (Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
            {
                var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "DefaultError");

                return new UpdateMediaChaptersResponse()
                {
                    HttpMeta = new Models.Components.HttpMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    },
                    DefaultError = obj
                };
            }

            throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }

        public async Task<UpdateMediaNamedEntitiesResponse> UpdateNamedEntitiesAsync(string mediaId, UpdateMediaNamedEntitiesRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new UpdateMediaNamedEntitiesRequest()
            {
                MediaId = mediaId,
                Body = body,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/on-demand/{mediaId}/named-entities", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Patch, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "update-media-named-entities", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if (responseStatusCode == 200)
            {
                if (Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<UpdateMediaNamedEntitiesResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "UpdateMediaNamedEntitiesResponseBody");

                    return new UpdateMediaNamedEntitiesResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        },
                        Object = obj
                    };
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            if (responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }

            if (Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
            {
                var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "DefaultError");

                return new UpdateMediaNamedEntitiesResponse()
                {
                    HttpMeta = new Models.Components.HttpMetadata()
                    {
                        Response = httpResponse,
                        Request = httpRequest
                    },
                    DefaultError = obj
                };
            }

            throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
        }
    }
}