/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix
{
    using Fastpix.Hooks;
    using Fastpix.Models.Components;
    using Fastpix.Models.Errors;
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    using Fastpix.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Operations for video playback management
    /// </summary>
    public interface IPlayback
    {

        /// <summary>
        /// Create a playback ID
        /// 
        /// <remarks>
        /// You can create a new playback ID for a specific media asset. If you have already retrieved an existing `playbackId` using the &lt;a href=&quot;https://fastpix.com/docs/video-on-demand-api/manage-videos/get-media&quot;&gt;Get Media by ID&lt;/a&gt; endpoint for a media asset, you can use this endpoint to generate a new playback ID with a specified access policy. <br/>
        /// <br/>
        /// <br/>
        /// <br/>
        /// If you want to create a private playback ID for a media asset that already has a public playback ID, this endpoint also allows you to do so by specifying the desired access policy. <br/>
        /// <br/>
        /// #### How it works<br/>
        /// <br/>
        /// 1. Make a `POST` request to this endpoint, replacing `&lt;mediaId&gt;` with the `uploadId` or `id` of the media asset. <br/>
        /// <br/>
        /// 2. Include the `accessPolicy` in the request body with `private` or `public` as the value. <br/>
        /// <br/>
        /// 3. You receive a response containing the newly created playback ID with the specified access level.<br/>
        /// <br/>
        /// <br/>
        /// #### Example<br/>
        /// A video streaming service generates playback IDs for each media file when users request to view specific content. The video player then uses the playback ID to stream the video.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<CreateMediaPlaybackIdResponse> CreateAsync(string mediaId, CreateMediaPlaybackIdRequestBody? body = null, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);

        /// <summary>
        /// Get all playback IDs details for a media
        /// 
        /// <remarks>
        /// Retrieves all playback IDs associated with a given media asset, including each playback ID’s access policy and detailed access restrictions such as allowed or denied domains and user agents.<br/>
        /// <br/>
        /// **How it works:**<br/>
        /// 1. Send a `GET` request to this endpoint with the target `mediaId`.<br/>
        /// 2. The response includes an array of playback ID records with their respective access controls.<br/>
        /// <br/>
        /// **Use case:**<br/>
        /// Useful for validating and managing playback permissions programmatically, reviewing restriction settings, or powering an access control dashboard.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<ListPlaybackIdsResponse> ListAsync(string mediaId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);

        /// <summary>
        /// Delete a playback ID
        /// 
        /// <remarks>
        /// This endpoint deletes a specific playback ID associated with a media asset. Deleting a `playback ID` revokes access to the media content linked to that ID.<br/>
        /// <br/>
        /// <br/>
        /// #### How it works<br/>
        /// <br/>
        /// 1. Make a `DELETE` request to this endpoint, replacing `&lt;mediaId&gt;` with the unique ID of the media asset from which you want to delete the playback ID. <br/>
        /// <br/>
        /// 2. Include the `playbackId` you want to delete in the request body.<br/>
        /// <br/>
        /// #### Example<br/>
        /// <br/>
        /// Your platform offers limited-time access to premium content. When the subscription expires, you can revoke access to the content by deleting the associated playback ID, preventing users from streaming the video further.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<DeleteMediaPlaybackIdResponse> DeleteAsync(string mediaId, string playbackId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);

        /// <summary>
        /// Update domain restrictions for a playback ID
        /// 
        /// <remarks>
        /// This endpoint updates domain-level restrictions for a specific playback ID associated with a media asset.<br/>
        /// It allows you to restrict playback to specific domains or block known unauthorized domains.<br/>
        /// <br/>
        /// **How it works:**<br/>
        /// 1. Make a `PATCH` request to this endpoint with your desired domain access configuration.<br/>
        /// 2. Set a default policy (`allow` or `deny`) and specify domain names in the `allow` or `deny` lists.<br/>
        /// 3. This is commonly used to restrict video playback to your website or approved client domains.<br/>
        /// <br/>
        /// **Example:**<br/>
        /// A streaming service can allow playback only from `example.com` and deny all others by setting: `&quot;defaultPolicy&quot;: &quot;deny&quot;` and `&quot;allow&quot;: [&quot;example.com&quot;]`.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<UpdateDomainRestrictionsResponse> UpdateDomainRestrictionsAsync(string mediaId, string playbackId, UpdateDomainRestrictionsRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);

        /// <summary>
        /// Update user-agent restrictions for a playback ID
        /// 
        /// <remarks>
        /// This endpoint allows updating user-agent restrictions for a specific playback ID associated with a media asset. <br/>
        /// It can be used to allow or deny specific user-agents during playback request evaluation.<br/>
        /// <br/>
        /// **How it works:**<br/>
        /// 1. Make a `PATCH` request to this endpoint with your desired user-agent access configuration.<br/>
        /// 2. Specify a default policy (`allow` or `deny`) and provide specific `allow` or `deny` lists.<br/>
        /// 3. Use this to restrict access to specific browsers, devices, or bots.<br/>
        /// <br/>
        /// **Example:**<br/>
        /// A developer may configure a playback ID to deny access from known scraping user-agents while allowing all others by default.<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<UpdateUserAgentRestrictionsResponse> UpdateUserAgentRestrictionsAsync(string mediaId, string playbackId, UpdateUserAgentRestrictionsRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);
    }

    /// <summary>
    /// Operations for video playback management
    /// </summary>
    public class Playback: IPlayback
    {
        public SdkConfig SDKConfiguration { get; private set; }

        private const string ContentTypeJson = "application/json";
        private const string UnknownContentTypeMessage = "Unknown content type received";
        private const string ApiErrorMessage = "API error occurred";
        private const string UserAgentHeader = "user-agent";

        private static RetryConfig BuildDefaultRetryConfig()
        {
            var backoff = new BackoffStrategy(
                initialIntervalMs: 1000L,
                maxIntervalMs: 10000L,
                maxElapsedTimeMs: 3600000L,
                exponent: 1.5
            );
            return new RetryConfig(
                strategy: RetryConfig.RetryStrategy.BACKOFF,
                backoff: backoff,
                retryConnectionErrors: true
            );
        }

        private async Task<HttpResponseMessage> SendWithHooksAsync(Fastpix.Utils.Retries.Retries retries, HookContext hookCtx)
        {
            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int statusCode = (int)httpResponse.StatusCode;

                if (statusCode >= 400 && statusCode < 600)
                {
                    var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (hooked != null)
                    {
                        httpResponse = hooked;
                    }
                }
            }
            catch (Exception error)
            {
                var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (hooked == null)
                {
                    throw;
                }
                httpResponse = hooked;
            }

            return await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);
        }

        private static T DeserializeOrThrow<T>(string body, HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, NullValueHandling nullValueHandling, string typeName)
        {
            try
            {
                return ResponseBodyDeserializer.DeserializeNotNull<T>(body, nullValueHandling);
            }
            catch (Exception ex)
            {
                throw new ResponseValidationException($"Failed to deserialize response body into {typeName}.", httpRequest, httpResponse, body, ex);
            }
        }

        public Playback(SdkConfig config)
        {
            SDKConfiguration = config;
        }

        public async Task<CreateMediaPlaybackIdResponse> CreateAsync(string mediaId, CreateMediaPlaybackIdRequestBody? body = null, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new CreateMediaPlaybackIdRequest()
            {
                MediaId = mediaId,
                Body = body,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/on-demand/{mediaId}/playback-ids", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Post, urlString);
            httpRequest.Headers.Add(UserAgentHeader, SDKConfiguration.UserAgent);

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, true);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "create-media-playback-id", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 201)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<CreateMediaPlaybackIdResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "CreateMediaPlaybackIdResponseBody");

                    var response = new CreateMediaPlaybackIdResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, nameof(DefaultError));

                    var response = new CreateMediaPlaybackIdResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }

        public async Task<ListPlaybackIdsResponse> ListAsync(string mediaId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new ListPlaybackIdsRequest()
            {
                MediaId = mediaId,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/on-demand/{mediaId}/playback-ids", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add(UserAgentHeader, SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "list-playback-ids", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<ListPlaybackIdsResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "ListPlaybackIdsResponseBody");

                    var response = new ListPlaybackIdsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, nameof(DefaultError));

                    var response = new ListPlaybackIdsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }

        public async Task<DeleteMediaPlaybackIdResponse> DeleteAsync(string mediaId, string playbackId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new DeleteMediaPlaybackIdRequest()
            {
                MediaId = mediaId,
                PlaybackId = playbackId,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/on-demand/{mediaId}/playback-ids", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Delete, urlString);
            httpRequest.Headers.Add(UserAgentHeader, SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "delete-media-playback-id", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DeleteMediaPlaybackIdResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "DeleteMediaPlaybackIdResponseBody");

                    var response = new DeleteMediaPlaybackIdResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, nameof(DefaultError));

                    var response = new DeleteMediaPlaybackIdResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }

        public async Task<UpdateDomainRestrictionsResponse> UpdateDomainRestrictionsAsync(string mediaId, string playbackId, UpdateDomainRestrictionsRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new UpdateDomainRestrictionsRequest()
            {
                MediaId = mediaId,
                PlaybackId = playbackId,
                Body = body,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/on-demand/{mediaId}/playback-ids/{playbackId}/domains", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Patch, urlString);
            httpRequest.Headers.Add(UserAgentHeader, SDKConfiguration.UserAgent);

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "update-domain-restrictions", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<UpdateDomainRestrictionsResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "UpdateDomainRestrictionsResponseBody");

                    var response = new UpdateDomainRestrictionsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, nameof(DefaultError));

                    var response = new UpdateDomainRestrictionsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }

        public async Task<UpdateUserAgentRestrictionsResponse> UpdateUserAgentRestrictionsAsync(string mediaId, string playbackId, UpdateUserAgentRestrictionsRequestBody body, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new UpdateUserAgentRestrictionsRequest()
            {
                MediaId = mediaId,
                PlaybackId = playbackId,
                Body = body,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/on-demand/{mediaId}/playback-ids/{playbackId}/user-agents", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Patch, urlString);
            httpRequest.Headers.Add(UserAgentHeader, SDKConfiguration.UserAgent);

            var serializedBody = RequestBodySerializer.Serialize(request, "Body", "json", false, false);
            if (serializedBody != null)
            {
                httpRequest.Content = serializedBody;
            }

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "update-user-agent-restrictions", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<UpdateUserAgentRestrictionsResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "UpdateUserAgentRestrictionsResponseBody");

                    var response = new UpdateUserAgentRestrictionsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, nameof(DefaultError));

                    var response = new UpdateUserAgentRestrictionsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }
    }
}