/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix
{
    using Fastpix.Hooks;
    using Fastpix.Models.Components;
    using Fastpix.Models.Errors;
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    using Fastpix.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading;
    using System.Threading.Tasks;

    public interface ISimulcastStream
    {

        /// <summary>
        /// Get a specific simulcast
        /// 
        /// <remarks>
        /// Retrieves the details of a specific simulcast associated with a parent live stream. By providing both the `streamId` of the parent stream and the `simulcastId`, FastPix returns detailed information about the simulcast, such as the stream URL, the status of the simulcast, and metadata. <br/>
        /// <br/>
        /// #### Example<br/>
        /// This endpoint can be used to verify the status of the simulcast on external platforms before the live stream begins. For example, before starting a live gaming event, the organizer wants to ensure that the simulcast to Twitch is set up correctly. They retrieve the simulcast information to confirm that everything is properly configured.
        /// </remarks>
        /// </summary>
        Task<GetSpecificSimulcastOfStreamResponse> GetSpecificAsync(string streamId, string simulcastId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);
    }

    public class SimulcastStream: ISimulcastStream
    {
        public SdkConfig SDKConfiguration { get; private set; }

        private const string ContentTypeJson = "application/json";
        private const string UnknownContentTypeMessage = "Unknown content type received";
        private const string ApiErrorMessage = "API error occurred";

        private static RetryConfig BuildDefaultRetryConfig()
        {
            var backoff = new BackoffStrategy(
                initialIntervalMs: 1000L,
                maxIntervalMs: 10000L,
                maxElapsedTimeMs: 3600000L,
                exponent: 1.5
            );
            return new RetryConfig(
                strategy: RetryConfig.RetryStrategy.BACKOFF,
                backoff: backoff,
                retryConnectionErrors: true
            );
        }

        private async Task<HttpResponseMessage> SendWithHooksAsync(Fastpix.Utils.Retries.Retries retries, HookContext hookCtx)
        {
            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int statusCode = (int)httpResponse.StatusCode;

                if (statusCode >= 400 && statusCode < 600)
                {
                    var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (hooked != null)
                    {
                        httpResponse = hooked;
                    }
                }
            }
            catch (Exception error)
            {
                var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (hooked == null)
                {
                    throw;
                }
                httpResponse = hooked;
            }

            return await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);
        }

        private static T DeserializeOrThrow<T>(string body, HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, NullValueHandling nullValueHandling, string typeName)
        {
            try
            {
                return ResponseBodyDeserializer.DeserializeNotNull<T>(body, nullValueHandling);
            }
            catch (Exception ex)
            {
                throw new ResponseValidationException($"Failed to deserialize response body into {typeName}.", httpRequest, httpResponse, body, ex);
            }
        }

        public SimulcastStream(SdkConfig config)
        {
            SDKConfiguration = config;
        }

        public async Task<GetSpecificSimulcastOfStreamResponse> GetSpecificAsync(string streamId, string simulcastId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new GetSpecificSimulcastOfStreamRequest()
            {
                StreamId = streamId,
                SimulcastId = simulcastId,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/live/streams/{streamId}/simulcast/{simulcastId}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "get-specific-simulcast-of-stream", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<SimulcastResponse>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "SimulcastResponse");

                    var response = new GetSpecificSimulcastOfStreamResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.SimulcastResponse = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "DefaultError");

                    var response = new GetSpecificSimulcastOfStreamResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }
    }
}