/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix
{
    using Fastpix.Hooks;
    using Fastpix.Models.Components;
    using Fastpix.Models.Errors;
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    using Fastpix.Utils.Retries;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Operations involving views
    /// </summary>
    public interface IViews
    {

        /// <summary>
        /// List video views
        /// 
        /// <remarks>
        /// Retrieves a list of video views that fall within the specified filters and have been completed within a defined timespan. It lets you to analyse viewer interactions with your video content effectively. <br/>
        /// <br/>
        /// <br/>
        /// #### How it works<br/>
        /// <br/>
        ///   1. Send a `GET` request to this endpoint with the desired query parameters. <br/>
        /// <br/>
        ///   2. Specify the timespan for which you want to retrieve the video views using the `timespan[]` parameter. <br/>
        /// <br/>
        ///   3. Filter the views based on dimensions such as browser, device, video title, viewer ID, etc., using the `filterby[]` parameter. Get the dimensions by calling &lt;a href=&quot;https://fastpix.com/docs/video-data-api/dimensions/list-dimensions&quot;&gt;list the dimensions&lt;/a&gt; endpoint. <br/>
        /// <br/>
        ///   4. Paginate the results using the `limit` and `offset` parameters. <br/>
        /// <br/>
        ///   5. You can also filter by `viewerId`, `errorCode`, `orderBy` a specific field, and `sortOrder` in ascending or descending order. <br/>
        /// <br/>
        ///   6. You receive a response containing the list of video views matching the specified criteria.<br/>
        /// <br/>
        /// Each view in the response includes a unique `viewId`. You can use this `viewId` with the  &lt;a href=&quot;https://fastpix.com/docs/video-data-api/views/get-video-view-details&quot;&gt;Get Video View Details&lt;/a&gt; endpoint to retrieve more detailed information about that specific view.<br/>
        /// <br/>
        /// <br/>
        /// #### Example<br/>
        /// <br/>
        /// If you manage a video streaming service and want to analyze content performance across devices and browsers. By calling the List Video Views endpoint with filters such as `browser_name` and `device_type`, you can identify which platforms are most popular with your audience. This information helps optimize content for widely used platforms and troubleshoot playback issues on less common devices.<br/>
        /// <br/>
        /// <br/>
        ///   Related guide: &lt;a href=&quot;https://fastpix.com/docs/concepts/audience-metrics&quot;&gt;Audience metrics&lt;/a&gt;, &lt;a href=&quot;https://fastpix.com/docs/working-with-video-data/explore-the-dashboard#1-views-dashboard&quot;&gt;Views dashboard&lt;/a&gt;
        /// </remarks>
        /// </summary>
        Task<ListVideoViewsResponse> ListAsync(ListVideoViewsRequest? request = null, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);

        /// <summary>
        /// Get details of video view
        /// 
        /// <remarks>
        /// Retrieves detailed information about a specific video view using its unique `viewId`. This provides insights into individual viewer interactions with your video content, helping you enhance user experience and improve engagement with your videos. <br/>
        /// <br/>
        /// To use this endpoint, send `GET` request with the `viewId`. The response includes detailed metrics and attributes related to the specified video view. <br/>
        /// <br/>
        /// <br/>
        /// #### Example<br/>
        /// <br/>
        /// If a developer receives a report of a poor viewing experience for a specific user. By using this endpoint with the users `viewId`, the developer can retrieve metrics like buffering duration, playback errors, and session length. This data allows the developer to pinpoint issues (such as poor connectivity or a browser-specific problem) and take steps to improve the user experience.<br/>
        /// <br/>
        /// <br/>
        /// Related guide: &lt;a href=&quot;https://fastpix.com/docs/concepts/what-video-data-do-we-capture#/&quot;&gt;What Video Data do we capture?&lt;/a&gt;
        /// </remarks>
        /// </summary>
        Task<GetVideoViewDetailsResponse> GetViewDetailsAsync(string viewId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);

        /// <summary>
        /// List by top content
        /// 
        /// <remarks>
        /// Retrieves a list of the top video views that fall within the specified filters and have been completed within a defined timespan. It lets you to identify the most popular content based on viewer interactions. <br/>
        /// <br/>
        /// #### How it works<br/>
        /// <br/>
        ///   1. Send a `GET` request to this endpoint with the desired query parameters. <br/>
        /// <br/>
        ///   2. Specify the timespan for which you want to retrieve the top content using the `timespan[]` parameter. <br/>
        /// <br/>
        ///   3. Filter the views based on dimensions such as browser, device, video title, etc., using the `filterby[]` parameter. <br/>
        /// <br/>
        ///   4. You can use `Limit` to control number of top views returned. <br/>
        /// <br/>
        ///   5. You receive a response containing the list of top video views matching the specified criteria.<br/>
        /// <br/>
        /// <br/>
        ///   Related guide: &lt;a href=&quot;https://fastpix.com/docs/working-with-video-data/identify-top-performing-content&quot;&gt;Get top-performing content&lt;/a&gt;<br/>
        /// 
        /// </remarks>
        /// </summary>
        Task<ListByTopContentResponse> ListByTopContentAsync(ListByTopContentTimespan? timespan = null, string? filterby = null, long? limit = 10, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null);
    }

    /// <summary>
    /// Operations involving views
    /// </summary>
    public class Views: IViews
    {
        public SdkConfig SDKConfiguration { get; private set; }

        private const string ContentTypeJson = "application/json";
        private const string UnknownContentTypeMessage = "Unknown content type received";
        private const string ApiErrorMessage = "API error occurred";

        private static RetryConfig BuildDefaultRetryConfig()
        {
            var backoff = new BackoffStrategy(
                initialIntervalMs: 1000L,
                maxIntervalMs: 10000L,
                maxElapsedTimeMs: 3600000L,
                exponent: 1.5
            );
            return new RetryConfig(
                strategy: RetryConfig.RetryStrategy.BACKOFF,
                backoff: backoff,
                retryConnectionErrors: true
            );
        }

        private async Task<HttpResponseMessage> SendWithHooksAsync(Fastpix.Utils.Retries.Retries retries, HookContext hookCtx)
        {
            HttpResponseMessage httpResponse;
            try
            {
                httpResponse = await retries.Run();
                int statusCode = (int)httpResponse.StatusCode;

                if (statusCode >= 400 && statusCode < 600)
                {
                    var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), httpResponse, null);
                    if (hooked != null)
                    {
                        httpResponse = hooked;
                    }
                }
            }
            catch (Exception error)
            {
                var hooked = await this.SDKConfiguration.Hooks.AfterErrorAsync(new AfterErrorContext(hookCtx), null, error);
                if (hooked == null)
                {
                    throw;
                }
                httpResponse = hooked;
            }

            return await this.SDKConfiguration.Hooks.AfterSuccessAsync(new AfterSuccessContext(hookCtx), httpResponse);
        }

        private static T DeserializeOrThrow<T>(string body, HttpRequestMessage httpRequest, HttpResponseMessage httpResponse, NullValueHandling nullValueHandling, string typeName)
        {
            try
            {
                return ResponseBodyDeserializer.DeserializeNotNull<T>(body, nullValueHandling);
            }
            catch (Exception ex)
            {
                throw new ResponseValidationException($"Failed to deserialize response body into {typeName}.", httpRequest, httpResponse, body, ex);
            }
        }

        public Views(SdkConfig config)
        {
            SDKConfiguration = config;
        }

        public async Task<ListVideoViewsResponse> ListAsync(ListVideoViewsRequest? request = null, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/data/viewlist", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "list_video_views", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<ListVideoViewsResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Include, "ListVideoViewsResponseBody");

                    var response = new ListVideoViewsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Include, "DefaultError");

                    var response = new ListVideoViewsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }

        public async Task<GetVideoViewDetailsResponse> GetViewDetailsAsync(string viewId, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new GetVideoViewDetailsRequest()
            {
                ViewId = viewId,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/data/viewlist/{viewId}", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "get_video_view_details", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<GetVideoViewDetailsResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "GetVideoViewDetailsResponseBody");

                    var response = new GetVideoViewDetailsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Ignore, "DefaultError");

                    var response = new GetVideoViewDetailsResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }

        public async Task<ListByTopContentResponse> ListByTopContentAsync(ListByTopContentTimespan? timespan = null, string? filterby = null, long? limit = 10, RetryConfig? retryConfig = null, CancellationToken? cancellationToken = null)
        {
            var request = new ListByTopContentRequest()
            {
                Timespan = timespan,
                Filterby = filterby,
                Limit = limit,
            };
            string baseUrl = this.SDKConfiguration.GetTemplatedServerUrl();
            var urlString = UrlBuilder.Build(baseUrl, "/data/viewlist/top-content", request, null);

            var httpRequest = new HttpRequestMessage(HttpMethod.Get, urlString);
            httpRequest.Headers.Add("user-agent", SDKConfiguration.UserAgent);

            if (SDKConfiguration.SecuritySource != null)
            {
                httpRequest = new SecurityMetadata(SDKConfiguration.SecuritySource).Apply(httpRequest);
            }

            var hookCtx = new HookContext(SDKConfiguration, baseUrl, "list_by_top_content", null, SDKConfiguration.SecuritySource, cancellationToken);

            httpRequest = await this.SDKConfiguration.Hooks.BeforeRequestAsync(new BeforeRequestContext(hookCtx), httpRequest);
            retryConfig ??= this.SDKConfiguration.RetryConfig ?? BuildDefaultRetryConfig();

            List<string> statusCodes = new List<string>
            {
                "408",
                "429",
                "500",
                "502",
                "503",
                "504",
            };

            Func<Task<HttpResponseMessage>> retrySend = async () =>
            {
                var _httpRequest = await SDKConfiguration.Client.CloneAsync(httpRequest);
                return await SDKConfiguration.Client.SendAsync(_httpRequest, cancellationToken);
            };
            var retries = new Fastpix.Utils.Retries.Retries(retrySend, retryConfig, statusCodes);

            HttpResponseMessage httpResponse = await SendWithHooksAsync(retries, hookCtx);

            var contentType = httpResponse.Content.Headers.ContentType?.MediaType;
            int responseStatusCode = (int)httpResponse.StatusCode;
            if(responseStatusCode == 200)
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<ListByTopContentResponseBody>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Include, "ListByTopContentResponseBody");

                    var response = new ListByTopContentResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.Object = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else if(responseStatusCode >= 400 && responseStatusCode < 600)
            {
                throw new Models.Errors.ApiException(ApiErrorMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
            else
            {
                if(Utilities.IsContentTypeMatch(ContentTypeJson, contentType))
                {
                    var httpResponseBody = await httpResponse.Content.ReadAsStringAsync();
                    var obj = DeserializeOrThrow<DefaultError>(httpResponseBody, httpRequest, httpResponse, NullValueHandling.Include, "DefaultError");

                    var response = new ListByTopContentResponse()
                    {
                        HttpMeta = new Models.Components.HttpMetadata()
                        {
                            Response = httpResponse,
                            Request = httpRequest
                        }
                    };
                    response.DefaultError = obj;
                    return response;
                }

                throw new Models.Errors.ApiException(UnknownContentTypeMessage, httpRequest, httpResponse, await httpResponse.Content.ReadAsStringAsync());
            }
        }
    }
}