//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Basic access policy for media content
    /// </summary>
    public enum BasicAccessPolicy
    {
        [JsonProperty("public")]
        Public,
        [JsonProperty("private")]
        Private,
    }

    public static class BasicAccessPolicyExtension
    {
        public static string Value(this BasicAccessPolicy value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static BasicAccessPolicy ToEnum(this string value)
        {
            foreach(var field in typeof(BasicAccessPolicy).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is BasicAccessPolicy)
                    {
                        return (BasicAccessPolicy)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum BasicAccessPolicy");
        }
    }

}