//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class BrowserNameDimensiondetails
    {

        /// <summary>
        /// The specific metric value calculated based on the applied filters.
        /// </summary>
        [JsonProperty("value")]
        public string Value { get; set; } = default!;

        /// <summary>
        /// The count of unique viewers who interacted with the content.
        /// </summary>
        [JsonProperty("uniqueCount")]
        public long? UniqueCount { get; set; }

        /// <summary>
        /// The count of viewers.
        /// </summary>
        [JsonProperty("count")]
        public long Count { get; set; } = default!;
    }
}