//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class ChaptersResponse
    {

        [JsonProperty("mediaId")]
        public string? MediaId { get; set; }

        [JsonProperty("isChaptersEnabled")]
        public bool? IsChaptersEnabled { get; set; }
    }
}