//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class CreateLiveStreamRequest
    {

        /// <summary>
        /// Displays the result of the playback settings.
        /// </summary>
        [JsonProperty("playbackSettings")]
        public PlaybackSettings PlaybackSettings { get; set; } = default!;

        /// <summary>
        /// Displays the result of the input Media settings.
        /// </summary>
        [JsonProperty("inputMediaSettings")]
        public InputMediaSettings InputMediaSettings { get; set; } = default!;
    }
}