//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class CreateMediaRequestUserAgents
    {

        /// <summary>
        /// Policy action type
        /// </summary>
        [JsonProperty("defaultPolicy")]
        public PolicyAction? DefaultPolicy { get; set; }

        /// <summary>
        /// A list of user agents (identified by string names or patterns) that are explicitly allowed access. <br/>
        /// 
        /// <remarks>
        /// This list is only effective when the `defaultPolicy` is set to `deny`.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("allow")]
        public List<string>? Allow { get; set; }

        /// <summary>
        /// A list of user agents (identified by string names or patterns) that are explicitly denied access. <br/>
        /// 
        /// <remarks>
        /// This list is only effective when the `defaultPolicy` is set to `allow`.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("deny")]
        public List<string>? Deny { get; set; }
    }
}