/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The quality tier applied to the media.
    /// </summary>
    // Open enum: unknown server values are preserved as the raw string instead of throwing.
    [JsonConverter(typeof(OpenEnumConverter))]
    public sealed class CreateMediaResponseMediaQuality : IEquatable<CreateMediaResponseMediaQuality>
    {
        public static readonly CreateMediaResponseMediaQuality Standard = new("standard");
        public static readonly CreateMediaResponseMediaQuality Pro = new("pro");
        public static readonly CreateMediaResponseMediaQuality Premium = new("premium");
        private static readonly Dictionary<string, CreateMediaResponseMediaQuality> Known = new()
        {
            ["standard"] = Standard,
            ["pro"] = Pro,
            ["premium"] = Premium,
        };

        private CreateMediaResponseMediaQuality(string value)
        {
            Value = value;
        }

        public string Value { get; }

        // Returns the shared instance for a known value, otherwise a wrapper carrying the raw string.
        public static CreateMediaResponseMediaQuality Of(string value)
        {
            return Known.TryGetValue(value, out var known) ? known : new CreateMediaResponseMediaQuality(value);
        }

        // False when the server sent a value this SDK version does not recognise.
        public bool IsKnown => Known.ContainsKey(Value);

        public override string ToString() => Value;

        public override bool Equals(object? obj) => obj is CreateMediaResponseMediaQuality other && other.Value == Value;

        public bool Equals(CreateMediaResponseMediaQuality? other) => other is not null && other.Value == Value;

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(CreateMediaResponseMediaQuality? left, CreateMediaResponseMediaQuality? right) => Equals(left, right);

        public static bool operator !=(CreateMediaResponseMediaQuality? left, CreateMediaResponseMediaQuality? right) => !Equals(left, right);
    }
}
