//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class CreateMediaRequestAccessRestrictions
    {

        [JsonProperty("domains")]
        public CreateMediaRequestDomains? Domains { get; set; }

        [JsonProperty("userAgents")]
        public CreateMediaRequestUserAgents? UserAgents { get; set; }
    }
}