/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Restrictions based on the originating domain of a request
    /// </summary>
    public class DomainRestrictions
    {

        /// <summary>
        /// Policy action type
        /// </summary>
        [JsonProperty("defaultPolicy")]
        public PolicyAction? DefaultPolicy { get; set; }

        /// <summary>
        /// A list of domain names or patterns that are explicitly allowed access
        /// </summary>
        [JsonProperty("allow")]
        public List<string>? Allow { get; set; }

        /// <summary>
        /// A list of domain names or patterns that are explicitly denied access
        /// </summary>
        [JsonProperty("deny")]
        public List<string>? Deny { get; set; }
    }
}