/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class GetAllSigningKeysResponse
    {

        /// <summary>
        /// Shows the request status. Returns true for success and false for failure.
        /// </summary>
        [JsonProperty("success")]
        public bool? Success { get; set; }

        [JsonProperty("data")]
        public List<GetAllSigningKeysResponseDto>? Data { get; set; }

        /// <summary>
        /// Pagination organizes content into pages for better readability and navigation.
        /// </summary>
        [JsonProperty("pagination")]
        public SigningKeysPagination? Pagination { get; set; }
    }
}