/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class GetAllMediaResponseTrackType
    {
        private GetAllMediaResponseTrackType(string value) { Value = value; }

        public string Value { get; private set; }

        public static GetAllMediaResponseTrackType VideoTrackForGetAll { get { return new GetAllMediaResponseTrackType("VideoTrackForGetAll"); } }

        public static GetAllMediaResponseTrackType AudioTrack { get { return new GetAllMediaResponseTrackType("AudioTrack"); } }

        public static GetAllMediaResponseTrackType SubtitleTrack { get { return new GetAllMediaResponseTrackType("SubtitleTrack"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(GetAllMediaResponseTrackType v) { return v.Value; }
        public static GetAllMediaResponseTrackType FromString(string v) {
            switch(v) {
                case "VideoTrackForGetAll": return VideoTrackForGetAll;
                case "AudioTrack": return AudioTrack;
                case "SubtitleTrack": return SubtitleTrack;
                default: throw new ArgumentException("Invalid value for GetAllMediaResponseTrackType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((GetAllMediaResponseTrackType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(GetAllMediaResponseTrack.GetAllMediaResponseTrackConverter))]
    public class GetAllMediaResponseTrack
    {
        public GetAllMediaResponseTrack(GetAllMediaResponseTrackType type)
        {
            Type = type;
        }

        [FastpixMetadata("form:explode=true")]
        public VideoTrackForGetAll? VideoTrackForGetAll { get; set; }

        [FastpixMetadata("form:explode=true")]
        public AudioTrack? AudioTrack { get; set; }

        [FastpixMetadata("form:explode=true")]
        public SubtitleTrack? SubtitleTrack { get; set; }

        public GetAllMediaResponseTrackType Type { get; set; }
        public static GetAllMediaResponseTrack CreateVideoTrackForGetAll(VideoTrackForGetAll videoTrackForGetAll)
        {
            GetAllMediaResponseTrackType typ = GetAllMediaResponseTrackType.VideoTrackForGetAll;

            GetAllMediaResponseTrack res = new GetAllMediaResponseTrack(typ);
            res.VideoTrackForGetAll = videoTrackForGetAll;
            return res;
        }
        public static GetAllMediaResponseTrack CreateAudioTrack(AudioTrack audioTrack)
        {
            GetAllMediaResponseTrackType typ = GetAllMediaResponseTrackType.AudioTrack;

            GetAllMediaResponseTrack res = new GetAllMediaResponseTrack(typ);
            res.AudioTrack = audioTrack;
            return res;
        }
        public static GetAllMediaResponseTrack CreateSubtitleTrack(SubtitleTrack subtitleTrack)
        {
            GetAllMediaResponseTrackType typ = GetAllMediaResponseTrackType.SubtitleTrack;

            GetAllMediaResponseTrack res = new GetAllMediaResponseTrack(typ);
            res.SubtitleTrack = subtitleTrack;
            return res;
        }

        public class GetAllMediaResponseTrackConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(GetAllMediaResponseTrack);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new GetAllMediaResponseTrack(GetAllMediaResponseTrackType.VideoTrackForGetAll)
                    {
                        VideoTrackForGetAll = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<VideoTrackForGetAll>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(VideoTrackForGetAll), new GetAllMediaResponseTrack(GetAllMediaResponseTrackType.VideoTrackForGetAll), "VideoTrackForGetAll"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new GetAllMediaResponseTrack(GetAllMediaResponseTrackType.AudioTrack)
                    {
                        AudioTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AudioTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AudioTrack), new GetAllMediaResponseTrack(GetAllMediaResponseTrackType.AudioTrack), "AudioTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new GetAllMediaResponseTrack(GetAllMediaResponseTrackType.SubtitleTrack)
                    {
                        SubtitleTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SubtitleTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SubtitleTrack), new GetAllMediaResponseTrack(GetAllMediaResponseTrackType.SubtitleTrack), "SubtitleTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                GetAllMediaResponseTrack res = (GetAllMediaResponseTrack)value;

                if (res.VideoTrackForGetAll != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.VideoTrackForGetAll));
                    return;
                }

                if (res.AudioTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AudioTrack));
                    return;
                }

                if (res.SubtitleTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SubtitleTrack));
                    return;
                }
            }

        }

    }
}