/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The quality tier applied to the media.
    /// </summary>
    // Open enum: unknown server values are preserved as the raw string instead of throwing.
    [JsonConverter(typeof(OpenEnumConverter))]
    public sealed class GetAllMediaResponseMediaQuality : IEquatable<GetAllMediaResponseMediaQuality>
    {
        public static readonly GetAllMediaResponseMediaQuality Standard = new("standard");
        public static readonly GetAllMediaResponseMediaQuality Pro = new("pro");
        public static readonly GetAllMediaResponseMediaQuality Premium = new("premium");
        private static readonly Dictionary<string, GetAllMediaResponseMediaQuality> Known = new()
        {
            ["standard"] = Standard,
            ["pro"] = Pro,
            ["premium"] = Premium,
        };

        private GetAllMediaResponseMediaQuality(string value)
        {
            Value = value;
        }

        public string Value { get; }

        // Returns the shared instance for a known value, otherwise a wrapper carrying the raw string.
        public static GetAllMediaResponseMediaQuality Of(string value)
        {
            return Known.TryGetValue(value, out var known) ? known : new GetAllMediaResponseMediaQuality(value);
        }

        // False when the server sent a value this SDK version does not recognise.
        public bool IsKnown => Known.ContainsKey(Value);

        public override string ToString() => Value;

        public override bool Equals(object? obj) => obj is GetAllMediaResponseMediaQuality other && other.Value == Value;

        public bool Equals(GetAllMediaResponseMediaQuality? other) => other is not null && other.Value == Value;

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(GetAllMediaResponseMediaQuality? left, GetAllMediaResponseMediaQuality? right) => Equals(left, right);

        public static bool operator !=(GetAllMediaResponseMediaQuality? left, GetAllMediaResponseMediaQuality? right) => !Equals(left, right);
    }
}
