/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The quality tier applied to the media.
    /// </summary>
    public enum GetMediaResponseMediaQuality
    {
        [JsonProperty("standard")]
        Standard,
        [JsonProperty("pro")]
        Pro,
        [JsonProperty("premium")]
        Premium,
    }

    public static class GetMediaResponseMediaQualityExtension
    {
        public static string Value(this GetMediaResponseMediaQuality value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetMediaResponseMediaQuality ToEnum(this string value)
        {
            foreach(var field in typeof(GetMediaResponseMediaQuality).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetMediaResponseMediaQuality)
                    {
                        return (GetMediaResponseMediaQuality)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetMediaResponseMediaQuality");
        }
    }

}