/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Determines the media&apos;s status, which can be one of the possible values.
    /// </summary>
    public enum GetMediaResponseStatus
    {
        [JsonProperty("Created")]
        Created,
        [JsonProperty("Downloading")]
        Downloading,
        [JsonProperty("Downloaded")]
        Downloaded,
        [JsonProperty("Validating")]
        Validating,
        [JsonProperty("In Queue")]
        InQueue,
        [JsonProperty("Processing")]
        Processing,
        [JsonProperty("Ready")]
        Ready,
        [JsonProperty("Failed")]
        Failed,
    }

    public static class GetMediaResponseStatusExtension
    {
        public static string Value(this GetMediaResponseStatus value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static GetMediaResponseStatus ToEnum(this string value)
        {
            foreach(var field in typeof(GetMediaResponseStatus).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is GetMediaResponseStatus)
                    {
                        return (GetMediaResponseStatus)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum GetMediaResponseStatus");
        }
    }

}