/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The actual resolution of the uploaded media. This represents the native quality of the source media.
    /// </summary>
    // Open enum: unknown server values are preserved as the raw string instead of throwing.
    [JsonConverter(typeof(OpenEnumConverter))]
    public sealed class GetMediaDetailResponseSourceResolution : IEquatable<GetMediaDetailResponseSourceResolution>
    {
        public static readonly GetMediaDetailResponseSourceResolution TwoThousandOneHundredAndSixtyp = new("2160p");
        public static readonly GetMediaDetailResponseSourceResolution TwoThousandOneHundredAndSixty = new("2160");
        public static readonly GetMediaDetailResponseSourceResolution OneThousandFourHundredAndFortyp = new("1440p");
        public static readonly GetMediaDetailResponseSourceResolution OneThousandFourHundredAndForty = new("1440");
        public static readonly GetMediaDetailResponseSourceResolution OneThousandAndEightyp = new("1080p");
        public static readonly GetMediaDetailResponseSourceResolution OneThousandAndEighty = new("1080");
        public static readonly GetMediaDetailResponseSourceResolution SevenHundredAndTwentyp = new("720p");
        public static readonly GetMediaDetailResponseSourceResolution SevenHundredAndTwenty = new("720");
        public static readonly GetMediaDetailResponseSourceResolution FourHundredAndEightyp = new("480p");
        public static readonly GetMediaDetailResponseSourceResolution FourHundredAndEighty = new("480");
        public static readonly GetMediaDetailResponseSourceResolution ThreeHundredAndSixtyp = new("360p");
        public static readonly GetMediaDetailResponseSourceResolution ThreeHundredAndSixty = new("360");
        private static readonly Dictionary<string, GetMediaDetailResponseSourceResolution> Known = new()
        {
            ["2160p"] = TwoThousandOneHundredAndSixtyp,
            ["2160"] = TwoThousandOneHundredAndSixty,
            ["1440p"] = OneThousandFourHundredAndFortyp,
            ["1440"] = OneThousandFourHundredAndForty,
            ["1080p"] = OneThousandAndEightyp,
            ["1080"] = OneThousandAndEighty,
            ["720p"] = SevenHundredAndTwentyp,
            ["720"] = SevenHundredAndTwenty,
            ["480p"] = FourHundredAndEightyp,
            ["480"] = FourHundredAndEighty,
            ["360p"] = ThreeHundredAndSixtyp,
            ["360"] = ThreeHundredAndSixty,
        };

        private GetMediaDetailResponseSourceResolution(string value)
        {
            Value = value;
        }

        public string Value { get; }

        // Returns the shared instance for a known value, otherwise a wrapper carrying the raw string.
        public static GetMediaDetailResponseSourceResolution Of(string value)
        {
            return Known.TryGetValue(value, out var known) ? known : new GetMediaDetailResponseSourceResolution(value);
        }

        // False when the server sent a value this SDK version does not recognise.
        public bool IsKnown => Known.ContainsKey(Value);

        public override string ToString() => Value;

        public override bool Equals(object? obj) => obj is GetMediaDetailResponseSourceResolution other && other.Value == Value;

        public bool Equals(GetMediaDetailResponseSourceResolution? other) => other is not null && other.Value == Value;

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(GetMediaDetailResponseSourceResolution? left, GetMediaDetailResponseSourceResolution? right) => Equals(left, right);

        public static bool operator !=(GetMediaDetailResponseSourceResolution? left, GetMediaDetailResponseSourceResolution? right) => !Equals(left, right);
    }
}
