//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Pagination organizes content into pages for better readability and navigation.
    /// </summary>
    public class LiveStreamPagination
    {

        /// <summary>
        /// It gives the total number of media assets that are accessible overall.
        /// </summary>
        [JsonProperty("totalRecords")]
        public long? TotalRecords { get; set; }

        /// <summary>
        /// Determines the current point for data retrieval within a paginated list.
        /// </summary>
        [JsonProperty("currentOffset")]
        public long? CurrentOffset { get; set; }

        /// <summary>
        /// The offset count is expressed as total records by limit.
        /// </summary>
        [JsonProperty("offsetCount")]
        public long? OffsetCount { get; set; }
    }
}