/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The maximum resolution specified by the user for the media.
    /// </summary>
    public enum LiveMediaClipsMaxResolution
    {
        [JsonProperty("2160p")]
        TwoThousandOneHundredAndSixtyp,
        [JsonProperty("1440p")]
        OneThousandFourHundredAndFortyp,
        [JsonProperty("1080p")]
        OneThousandAndEightyp,
        [JsonProperty("720p")]
        SevenHundredAndTwentyp,
        [JsonProperty("480p")]
        FourHundredAndEightyp,
    }

    public static class LiveMediaClipsMaxResolutionExtension
    {
        public static string Value(this LiveMediaClipsMaxResolution value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LiveMediaClipsMaxResolution ToEnum(this string value)
        {
            foreach(var field in typeof(LiveMediaClipsMaxResolution).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LiveMediaClipsMaxResolution)
                    {
                        return (LiveMediaClipsMaxResolution)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LiveMediaClipsMaxResolution");
        }
    }

}