/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The maximum resolution specified by the user for the media.
    /// </summary>
    // Open enum: unknown server values are preserved as the raw string instead of throwing.
    [JsonConverter(typeof(OpenEnumConverter))]
    public sealed class MediaMaxResolution : IEquatable<MediaMaxResolution>
    {
        public static readonly MediaMaxResolution TwoThousandOneHundredAndSixtyp = new("2160p");
        public static readonly MediaMaxResolution OneThousandFourHundredAndFortyp = new("1440p");
        public static readonly MediaMaxResolution OneThousandAndEightyp = new("1080p");
        public static readonly MediaMaxResolution SevenHundredAndTwentyp = new("720p");
        public static readonly MediaMaxResolution FourHundredAndEightyp = new("480p");
        private static readonly Dictionary<string, MediaMaxResolution> Known = new()
        {
            ["2160p"] = TwoThousandOneHundredAndSixtyp,
            ["1440p"] = OneThousandFourHundredAndFortyp,
            ["1080p"] = OneThousandAndEightyp,
            ["720p"] = SevenHundredAndTwentyp,
            ["480p"] = FourHundredAndEightyp,
        };

        private MediaMaxResolution(string value)
        {
            Value = value;
        }

        public string Value { get; }

        // Returns the shared instance for a known value, otherwise a wrapper carrying the raw string.
        public static MediaMaxResolution Of(string value)
        {
            return Known.TryGetValue(value, out var known) ? known : new MediaMaxResolution(value);
        }

        // False when the server sent a value this SDK version does not recognise.
        public bool IsKnown => Known.ContainsKey(Value);

        public override string ToString() => Value;

        public override bool Equals(object? obj) => obj is MediaMaxResolution other && other.Value == Value;

        public bool Equals(MediaMaxResolution? other) => other is not null && other.Value == Value;

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(MediaMaxResolution? left, MediaMaxResolution? right) => Equals(left, right);

        public static bool operator !=(MediaMaxResolution? left, MediaMaxResolution? right) => !Equals(left, right);
    }
}
