//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class MediaClipResponseTrack
    {

        /// <summary>
        /// The unique identifier for the media track.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The type of media track.
        /// </summary>
        [JsonProperty("type")]
        public MediaClipResponseType? Type { get; set; }

        /// <summary>
        /// The width of the video track (applicable to video only).
        /// </summary>
        [JsonProperty("width")]
        public long? Width { get; set; }

        /// <summary>
        /// The height of the video track (applicable to video only).
        /// </summary>
        [JsonProperty("height")]
        public long? Height { get; set; }

        /// <summary>
        /// The current processing status of the track.
        /// </summary>
        [JsonProperty("status")]
        public string? Status { get; set; }

        /// <summary>
        /// The language code of the audio or subtitle track.
        /// </summary>
        [JsonProperty("languageCode")]
        public string? LanguageCode { get; set; }

        /// <summary>
        /// The language name of the audio or subtitle track.
        /// </summary>
        [JsonProperty("languageName")]
        public string? LanguageName { get; set; }
    }
}