/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Response returned when an upload is cancelled.
    /// </summary>
    public class MediaCancelResponse
    {

        /// <summary>
        /// The unique identifier of the cancelled upload.
        /// </summary>
        [JsonProperty("uploadId")]
        public string? UploadId { get; set; }

        /// <summary>
        /// Indicates if the upload was a trial.
        /// </summary>
        [JsonProperty("trial")]
        public bool? Trial { get; set; }

        /// <summary>
        /// The status of the upload after cancellation.
        /// </summary>
        [JsonProperty("status")]
        public string? Status { get; set; }

        /// <summary>
        /// The upload URL (if available) after cancellation.
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }

        /// <summary>
        /// The timeout value for the upload.
        /// </summary>
        [JsonProperty("timeout")]
        public long? Timeout { get; set; } = null;

        /// <summary>
        /// CORS origin allowed for the upload.
        /// </summary>
        [JsonProperty("corsOrigin")]
        public string? CorsOrigin { get; set; }

        /// <summary>
        /// The maximum resolution allowed for the upload.
        /// </summary>
        [JsonProperty("maxResolution")]
        public string? MaxResolution { get; set; }

        /// <summary>
        /// The access policy for the upload.
        /// </summary>
        [JsonProperty("accessPolicy")]
        public string? AccessPolicy { get; set; }

        /// <summary>
        /// You can search for videos with specific key value pairs using metadata, when you tag a video in &quot;key&quot; : &quot;value&quot; pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; }

        /// <summary>
        /// Title of the media file.
        /// </summary>
        [JsonProperty("title")]
        public string? Title { get; set; } = null;

        /// <summary>
        /// The unique identifier of the user who created this media.
        /// </summary>
        [JsonProperty("creatorId")]
        public string? CreatorId { get; set; } = null;
    }
}