/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Retrieves overall values for a specified metric
    /// </summary>
    public class MetricsOverallDataDetails
    {

        /// <summary>
        /// metric value calculated based on the applied filters.
        /// </summary>
        [JsonProperty("value")]
        public double? Value { get; set; } = null;

        /// <summary>
        /// Total time watched across all views, represented in milliseconds.
        /// </summary>
        [JsonProperty("totalWatchTime")]
        public long? TotalWatchTime { get; set; } = null;

        /// <summary>
        /// The count of unique viewers who interacted with the content.
        /// </summary>
        [JsonProperty("uniqueViews")]
        public long? UniqueViews { get; set; } = null;

        /// <summary>
        /// The total number of views recorded.
        /// </summary>
        [JsonProperty("totalViews")]
        public long? TotalViews { get; set; } = null;

        /// <summary>
        /// Total time spent playing the video, represented in milliseconds.
        /// </summary>
        [JsonProperty("totalPlayTime")]
        public long? TotalPlayTime { get; set; } = null;

        /// <summary>
        /// A global metric value that reflects the overall performance of the specified metric across the entire dataset for the given timespan.
        /// </summary>
        [JsonProperty("globalValue")]
        public double? GlobalValue { get; set; } = null;
    }
}