/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Retrieves breakdown values for a specified metric and timespan
    /// </summary>
    public class MetricsTimeseriesmetadataDetails
    {

        /// <summary>
        /// the unit for aggregating the timeseries data.
        /// </summary>
        [JsonProperty("granularity")]
        public string? Granularity { get; set; }

        /// <summary>
        /// defines the field or dimension on which the aggregation is to be   applied.
        /// </summary>
        [JsonProperty("aggregation")]
        public string? Aggregation { get; set; }
    }
}