/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// File extension of the downloadable rendition.
    /// </summary>
    // Open enum: unknown server values are preserved as the raw string instead of throwing.
    [JsonConverter(typeof(OpenEnumConverter))]
    public sealed class Mp4SupportExt : IEquatable<Mp4SupportExt>
    {
        public static readonly Mp4SupportExt Mp4 = new("mp4");
        public static readonly Mp4SupportExt M4a = new("m4a");
        private static readonly Dictionary<string, Mp4SupportExt> Known = new()
        {
            ["mp4"] = Mp4,
            ["m4a"] = M4a,
        };

        private Mp4SupportExt(string value)
        {
            Value = value;
        }

        public string Value { get; }

        // Returns the shared instance for a known value, otherwise a wrapper carrying the raw string.
        public static Mp4SupportExt Of(string value)
        {
            return Known.TryGetValue(value, out var known) ? known : new Mp4SupportExt(value);
        }

        // False when the server sent a value this SDK version does not recognise.
        public bool IsKnown => Known.ContainsKey(Value);

        public override string ToString() => Value;

        public override bool Equals(object? obj) => obj is Mp4SupportExt other && other.Value == Value;

        public bool Equals(Mp4SupportExt? other) => other is not null && other.Value == Value;

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(Mp4SupportExt? left, Mp4SupportExt? right) => Equals(left, right);

        public static bool operator !=(Mp4SupportExt? left, Mp4SupportExt? right) => !Equals(left, right);
    }
}
