/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Generation status of this MP4 rendition.
    /// </summary>
    // Open enum: unknown server values are preserved as the raw string instead of throwing.
    [JsonConverter(typeof(OpenEnumConverter))]
    public sealed class Mp4SupportStatus : IEquatable<Mp4SupportStatus>
    {
        public static readonly Mp4SupportStatus Preparing = new("preparing");
        public static readonly Mp4SupportStatus Ready = new("ready");
        public static readonly Mp4SupportStatus Failed = new("failed");
        private static readonly Dictionary<string, Mp4SupportStatus> Known = new()
        {
            ["preparing"] = Preparing,
            ["ready"] = Ready,
            ["failed"] = Failed,
        };

        private Mp4SupportStatus(string value)
        {
            Value = value;
        }

        public string Value { get; }

        // Returns the shared instance for a known value, otherwise a wrapper carrying the raw string.
        public static Mp4SupportStatus Of(string value)
        {
            return Known.TryGetValue(value, out var known) ? known : new Mp4SupportStatus(value);
        }

        // False when the server sent a value this SDK version does not recognise.
        public bool IsKnown => Known.ContainsKey(Value);

        public override string ToString() => Value;

        public override bool Equals(object? obj) => obj is Mp4SupportStatus other && other.Value == Value;

        public bool Equals(Mp4SupportStatus? other) => other is not null && other.Value == Value;

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(Mp4SupportStatus? left, Mp4SupportStatus? right) => Equals(left, right);

        public static bool operator !=(Mp4SupportStatus? left, Mp4SupportStatus? right) => !Equals(left, right);
    }
}
