/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class PlayerViewCountType
    {
        private PlayerViewCountType(string value) { Value = value; }

        public string Value { get; private set; }

        public static PlayerViewCountType Str { get { return new PlayerViewCountType("str"); } }

        public static PlayerViewCountType Integer { get { return new PlayerViewCountType("integer"); } }

        public static PlayerViewCountType Null { get { return new PlayerViewCountType("null"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(PlayerViewCountType v) { return v.Value; }
        public static PlayerViewCountType FromString(string v) {
            switch(v) {
                case "str": return Str;
                case "integer": return Integer;
                case "null": return Null;
                default: throw new ArgumentException("Invalid value for PlayerViewCountType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((PlayerViewCountType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    /// <summary>
    /// Represents the total number of times the video player has been initialized or viewed for a specific session or video. This metric helps track playback engagement and identify view patterns across different players or sessions.<br/>
    /// 
    /// <remarks>
    /// 
    /// </remarks>
    /// </summary>
    [JsonConverter(typeof(PlayerViewCount.PlayerViewCountConverter))]
    public class PlayerViewCount
    {
        public PlayerViewCount(PlayerViewCountType type)
        {
            Type = type;
        }

        [FastpixMetadata("form:explode=true")]
        public string? Str { get; set; }

        [FastpixMetadata("form:explode=true")]
        public long? Integer { get; set; }

        public PlayerViewCountType Type { get; set; }
        public static PlayerViewCount CreateStr(string str)
        {
            PlayerViewCountType typ = PlayerViewCountType.Str;

            PlayerViewCount res = new PlayerViewCount(typ);
            res.Str = str;
            return res;
        }
        public static PlayerViewCount CreateInteger(long integer)
        {
            PlayerViewCountType typ = PlayerViewCountType.Integer;

            PlayerViewCount res = new PlayerViewCount(typ);
            res.Integer = integer;
            return res;
        }

        public static PlayerViewCount CreateNull()
        {
            PlayerViewCountType typ = PlayerViewCountType.Null;
            return new PlayerViewCount(typ);
        }

        public class PlayerViewCountConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(PlayerViewCount);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    return null;
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                if (json[0] == '"' && json[^1] == '"'){
                    return new PlayerViewCount(PlayerViewCountType.Str)
                    {
                        Str = json[1..^1]
                    };
                }

                try
                {
                    var converted = Convert.ToInt64(json);
                    return new PlayerViewCount(PlayerViewCountType.Integer)
                    {
                        Integer = converted
                    };
                }
                catch (System.FormatException)
                {
                    // try next option
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    writer.WriteRawValue("null");
                    return;
                }

                PlayerViewCount res = (PlayerViewCount)value;
                if (PlayerViewCountType.FromString(res.Type).Equals(PlayerViewCountType.Null))
                {
                    writer.WriteRawValue("null");
                    return;
                }

                if (res.Str != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Str));
                    return;
                }

                if (res.Integer != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.Integer));
                    return;
                }
            }

        }

    }
}