//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    
    public class PlaylistByIdResponseMediaList
    {

        /// <summary>
        /// Timestamp of media creation in the workspace.
        /// </summary>
        [JsonProperty("createdAt")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// Duration of the media in hh:mm:ss format.
        /// </summary>
        [JsonProperty("duration")]
        public string? Duration { get; set; }

        /// <summary>
        /// unique id of the particular media.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// source resolution of the media.
        /// </summary>
        [JsonProperty("sourceResolution")]
        public string? SourceResolution { get; set; }

        /// <summary>
        /// status of the media, only media with ready status will be added to playlist.
        /// </summary>
        [JsonProperty("status")]
        public string? Status { get; set; }

        /// <summary>
        /// thumbnail for the particular media.
        /// </summary>
        [JsonProperty("thumbnail")]
        public string? Thumbnail { get; set; }
    }
}