/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Controls access based on domains and user agents. Defines a default policy (either &quot;allow&quot; or &quot;deny&quot;) and provides lists for explicitly allowed or denied domains and user agents.
    /// </summary>
    public class PlaybackIdAccessRestrictions
    {

        /// <summary>
        /// Restrictions based on the originating domain of a request (for example, whether requests from certain websites must be allowed or blocked).
        /// </summary>
        [JsonProperty("domains")]
        public PlaybackIdDomains? Domains { get; set; }

        /// <summary>
        /// Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
        /// </summary>
        [JsonProperty("userAgents")]
        public PlaybackIdUserAgents? UserAgents { get; set; }
    }
}