//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Restrictions based on the user agent (which is typically a string sent by browsers or bots identifying themselves).
    /// </summary>
    public class PlaybackIdUserAgents
    {

        /// <summary>
        /// Policy action type
        /// </summary>
        [JsonProperty("defaultPolicy")]
        public PolicyAction? DefaultPolicy { get; set; }

        /// <summary>
        /// A list of specific user agents that are allowed to access the resource.
        /// </summary>
        [JsonProperty("allow")]
        public List<string>? Allow { get; set; }

        /// <summary>
        /// A list of specific user agents that are blocked.
        /// </summary>
        [JsonProperty("deny")]
        public List<string>? Deny { get; set; }
    }
}