/*
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Determines the insertion order of media into playlist.
    /// </summary>
    // Open enum: unknown server values are preserved as the raw string instead of throwing.
    [JsonConverter(typeof(OpenEnumConverter))]
    public sealed class PlaylistOrder : IEquatable<PlaylistOrder>
    {
        public static readonly PlaylistOrder CreatedDateASC = new("createdDate ASC");
        public static readonly PlaylistOrder CreatedDateDESC = new("createdDate DESC");
        private static readonly Dictionary<string, PlaylistOrder> Known = new()
        {
            ["createdDate ASC"] = CreatedDateASC,
            ["createdDate DESC"] = CreatedDateDESC,
        };

        private PlaylistOrder(string value)
        {
            Value = value;
        }

        public string Value { get; }

        // Returns the shared instance for a known value, otherwise a wrapper carrying the raw string.
        public static PlaylistOrder Of(string value)
        {
            return Known.TryGetValue(value, out var known) ? known : new PlaylistOrder(value);
        }

        // False when the server sent a value this SDK version does not recognise.
        public bool IsKnown => Known.ContainsKey(Value);

        public override string ToString() => Value;

        public override bool Equals(object? obj) => obj is PlaylistOrder other && other.Value == Value;

        public bool Equals(PlaylistOrder? other) => other is not null && other.Value == Value;

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(PlaylistOrder? left, PlaylistOrder? right) => Equals(left, right);

        public static bool operator !=(PlaylistOrder? left, PlaylistOrder? right) => !Equals(left, right);
    }
}
