//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Displays the result of the request.
    /// </summary>
    public class PlaybackIdResponse
    {

        /// <summary>
        /// It demonstrates whether the request is successful or not.
        /// </summary>
        [JsonProperty("success")]
        public bool? Success { get; set; }

        [JsonProperty("data")]
        public PlaybackIdResponseData? Data { get; set; }
    }
}