/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class PullVideoInputSegment2
    {

        /// <summary>
        /// The URL of the **video segment** to be added.  <br/>
        /// 
        /// <remarks>
        /// The URL must be **valid, publicly accessible, and downloadable** so that FastPix can retrieve and process the segment successfully.  <br/>
        /// Supported video formats include **MP4, MOV, MKV, and TS** for best compatibility and performance.<br/>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("url")]
        public string Url { get; set; } = default!;

        /// <summary>
        /// Flag indicating the segment should be inserted at the end.
        /// </summary>
        [JsonProperty("insertAtEnd")]
        public bool InsertAtEnd { get; set; } = default!;
    }
}