/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    
    public class Security
    {

        [FastpixMetadata("security:scheme=true,type=http,subType=basic,name=username")]
        public string Username { get; set; } = default!;

        [FastpixMetadata("security:scheme=true,type=http,subType=basic,name=password")]
        public string Password { get; set; } = default!;
    }
}