//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class SigningKeyWorkspaceDTO
    {

        /// <summary>
        /// FastPix generates a unique identifier for each workspace.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Designated title for the workspace.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Describes the type of a workspace.  Possible value: QA, staging, production, or development.
        /// </summary>
        [JsonProperty("workspaceType")]
        public string? WorkspaceType { get; set; }
    }
}