//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class SimulcastRequest
    {

        /// <summary>
        /// The RTMP hostname, combined with the application name, is crucial for connecting to third-party live streaming services and transmitting the live stream.
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }

        /// <summary>
        /// A unique stream key is generated for streaming, allowing the user to start streaming on any third-party platform using this key.
        /// </summary>
        [JsonProperty("streamKey")]
        public string? StreamKey { get; set; }
    }
}