/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class SourceAccessMediaTrackType
    {
        private SourceAccessMediaTrackType(string value) { Value = value; }

        public string Value { get; private set; }

        public static SourceAccessMediaTrackType VideoTrack { get { return new SourceAccessMediaTrackType("VideoTrack"); } }

        public static SourceAccessMediaTrackType AudioTrack { get { return new SourceAccessMediaTrackType("AudioTrack"); } }

        public static SourceAccessMediaTrackType SubtitleTrack { get { return new SourceAccessMediaTrackType("SubtitleTrack"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(SourceAccessMediaTrackType v) { return v.Value; }
        public static SourceAccessMediaTrackType FromString(string v) {
            switch(v) {
                case "VideoTrack": return VideoTrack;
                case "AudioTrack": return AudioTrack;
                case "SubtitleTrack": return SubtitleTrack;
                default: throw new ArgumentException("Invalid value for SourceAccessMediaTrackType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((SourceAccessMediaTrackType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(SourceAccessMediaTrack.SourceAccessMediaTrackConverter))]
    public class SourceAccessMediaTrack
    {
        public SourceAccessMediaTrack(SourceAccessMediaTrackType type)
        {
            Type = type;
        }

        [FastpixMetadata("form:explode=true")]
        public VideoTrack? VideoTrack { get; set; }

        [FastpixMetadata("form:explode=true")]
        public AudioTrack? AudioTrack { get; set; }

        [FastpixMetadata("form:explode=true")]
        public SubtitleTrack? SubtitleTrack { get; set; }

        public SourceAccessMediaTrackType Type { get; set; }
        public static SourceAccessMediaTrack CreateVideoTrack(VideoTrack videoTrack)
        {
            SourceAccessMediaTrackType typ = SourceAccessMediaTrackType.VideoTrack;

            SourceAccessMediaTrack res = new SourceAccessMediaTrack(typ);
            res.VideoTrack = videoTrack;
            return res;
        }
        public static SourceAccessMediaTrack CreateAudioTrack(AudioTrack audioTrack)
        {
            SourceAccessMediaTrackType typ = SourceAccessMediaTrackType.AudioTrack;

            SourceAccessMediaTrack res = new SourceAccessMediaTrack(typ);
            res.AudioTrack = audioTrack;
            return res;
        }
        public static SourceAccessMediaTrack CreateSubtitleTrack(SubtitleTrack subtitleTrack)
        {
            SourceAccessMediaTrackType typ = SourceAccessMediaTrackType.SubtitleTrack;

            SourceAccessMediaTrack res = new SourceAccessMediaTrack(typ);
            res.SubtitleTrack = subtitleTrack;
            return res;
        }

        public class SourceAccessMediaTrackConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(SourceAccessMediaTrack);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new SourceAccessMediaTrack(SourceAccessMediaTrackType.AudioTrack)
                    {
                        AudioTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AudioTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AudioTrack), new SourceAccessMediaTrack(SourceAccessMediaTrackType.AudioTrack), "AudioTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new SourceAccessMediaTrack(SourceAccessMediaTrackType.SubtitleTrack)
                    {
                        SubtitleTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SubtitleTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SubtitleTrack), new SourceAccessMediaTrack(SourceAccessMediaTrackType.SubtitleTrack), "SubtitleTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new SourceAccessMediaTrack(SourceAccessMediaTrackType.VideoTrack)
                    {
                        VideoTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<VideoTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(VideoTrack), new SourceAccessMediaTrack(SourceAccessMediaTrackType.VideoTrack), "VideoTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                SourceAccessMediaTrack res = (SourceAccessMediaTrack)value;

                if (res.VideoTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.VideoTrack));
                    return;
                }

                if (res.AudioTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AudioTrack));
                    return;
                }

                if (res.SubtitleTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SubtitleTrack));
                    return;
                }
            }

        }

    }
}