//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class TopErrorDetails
    {

        /// <summary>
        /// views affected by the specific errors.
        /// </summary>
        [JsonProperty("percentage", NullValueHandling = NullValueHandling.Include)]
        public TopErrorDetailsPercentage? Percentage { get; set; } = null;

        /// <summary>
        /// percentage of unique viewers affected by the specific error.
        /// </summary>
        [JsonProperty("uniqueViewersEffectedPercentage", NullValueHandling = NullValueHandling.Include)]
        public UniqueViewersEffectedPercentage? UniqueViewersEffectedPercentage { get; set; } = null;

        /// <summary>
        /// Information about the specific error.
        /// </summary>
        [JsonProperty("notes")]
        public string? Notes { get; set; } = null;

        /// <summary>
        /// error message or description.
        /// </summary>
        [JsonProperty("message")]
        public string? Message { get; set; } = null;

        /// <summary>
        /// The timestamp of when the error was last observed.
        /// </summary>
        [JsonProperty("lastSeen")]
        public string? LastSeen { get; set; } = null;

        /// <summary>
        /// unique identifier for the specific error.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; } = null;

        /// <summary>
        /// description of the specific error.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// Number of occurrences of the specific error.
        /// </summary>
        [JsonProperty("count")]
        public long? Count { get; set; } = null;

        /// <summary>
        /// Error code associated with the specific error.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; } = null;
    }
}