/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Displays the result of the request.
    /// </summary>
    public class UnusedDirectUpload
    {

        /// <summary>
        /// The unique identifier assigned to the media when created. The value must be a valid UUID.
        /// </summary>
        [JsonProperty("uploadId")]
        public string? UploadId { get; set; }

        /// <summary>
        /// Indicates if the upload was a trial.
        /// </summary>
        [JsonProperty("trial")]
        public bool? Trial { get; set; }

        /// <summary>
        /// Determines the media&apos;s status, which can be one of the possible values.
        /// </summary>
        [JsonProperty("status")]
        public UnusedDirectUploadStatus? Status { get; set; }

        /// <summary>
        /// The url hosts the media file for FastPix, which needs to be download to use further.  It supports formats like MP3, MP4, MOV, MKV, or TS, and includes text tracks for subtitles/CC (SRT file/VTT file). While FastPix can handle various audio and video formats and codecs, using standard inputs can help with optimal processing speed.
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }

        /// <summary>
        /// The duration set for the validity of the upload URL. If the upload isn’t completed within this timespan, it is marked as timed out.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("timeout")]
        public double? Timeout { get; set; } = 14400D;

        /// <summary>
        /// Upload media directly from a device using the url name or enter &quot;*&quot; to allow all.
        /// </summary>
        [JsonProperty("corsOrigin")]
        public string? CorsOrigin { get; set; }

        [JsonProperty("pushMediaSettings")]
        public UnusedDirectUploadResponse? PushMediaSettings { get; set; }
    }
}