/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class UnusedDirectUploadResponse
    {

        [JsonProperty("playbackIds")]
        public List<UnusedUploadsPlaybackId>? PlaybackIds { get; set; }

        /// <summary>
        /// You can search for videos with specific key value pairs using metadata, when you tag a video in &quot;key&quot; : &quot;value&quot; pairs. Dynamic metadata allows you to define a key that allows any value pair. You can have maximum of 255 characters and upto 10 entries are allowed.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; }

        /// <summary>
        /// The quality tier applied to the media.
        /// </summary>
        [JsonProperty("mediaQuality")]
        public UnusedDirectUploadResponseMediaQuality? MediaQuality { get; set; }

        /// <summary>
        /// The sourceAccess parameter determines whether the original media file is accessible. Set to true to enable access or false to restrict it.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("sourceAccess")]
        public bool? SourceAccess { get; set; }

        /// <summary>
        /// Enhance the quality and volume of the audio track. This is available for pre-recorded content only.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [JsonProperty("optimizeAudio")]
        public bool? OptimizeAudio { get; set; }
    }
}