//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Contains details about the track being added to the media file.
    /// </summary>
    public class UpdateTrackRequest
    {

        /// <summary>
        /// The direct URL of the track file. It should point to a valid audio or subtitle file.
        /// </summary>
        [JsonProperty("url")]
        public string? Url { get; set; }

        /// <summary>
        /// The BCP 47 language code representing the track&apos;s language.
        /// </summary>
        [JsonProperty("languageCode")]
        public string? LanguageCode { get; set; }

        /// <summary>
        /// The full name of the language corresponding to the `languageCode`.
        /// </summary>
        [JsonProperty("languageName")]
        public string? LanguageName { get; set; }
    }
}