//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Displays details about the reasons behind the request&apos;s failure.
    /// </summary>
    public class ValidationErrorResponseError
    {

        /// <summary>
        /// Displays the error code indicating the type of the error.
        /// </summary>
        [JsonProperty("code")]
        public long? Code { get; set; }

        /// <summary>
        /// A descriptive message providing more details for the error.
        /// </summary>
        [JsonProperty("message")]
        public string? Message { get; set; }

        /// <summary>
        /// It is an collection of objects, where each object contains information about a specific field and a corresponding error message.
        /// </summary>
        [JsonProperty("fields")]
        public List<FieldError>? Fields { get; set; }
    }
}