/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// A media consists of different media tracks, like video, audio, and subtitle, all combined.
    /// </summary>
    public class VideoTrack
    {

        /// <summary>
        /// FastPix generates a unique identifier for each track.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// Defines the type of input. This option is mandatory.
        /// </summary>
        [JsonProperty("type")]
        public string? Type { get; set; }

        /// <summary>
        /// Track width denotes the range of widths applicable to a specific track. Currently, this setting can be modified only for video tracks
        /// </summary>
        [JsonProperty("width")]
        public double? Width { get; set; }

        /// <summary>
        /// Track height denotes the range of height applicable to a specific track. Currently, this setting can be modified only for video tracks.
        /// </summary>
        [JsonProperty("height")]
        public double? Height { get; set; }

        /// <summary>
        /// Frame rate quantifies the speed at which frames are displayed per second. It represents the range of frames available for a specific track. The indeterminable frame rate of the input file is indicated by a value of -1.
        /// </summary>
        [JsonProperty("frameRate")]
        public string? FrameRate { get; set; }

        /// <summary>
        /// Indicates the current state of the track. &apos;available&apos; means the track has been processed successfully and is ready to be used or played.
        /// </summary>
        [JsonProperty("status")]
        public string? Status { get; set; }
    }
}