//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Returns the problem that has occured
    /// </summary>
    public class ViewNotFoundError
    {

        /// <summary>
        /// An error code indicating the type of the error.
        /// </summary>
        [JsonProperty("code")]
        public double? Code { get; set; }

        /// <summary>
        /// A descriptive message providing more details for the error.
        /// </summary>
        [JsonProperty("message")]
        public string? Message { get; set; }
    }
}