/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class ViewsCountResponse
    {

        /// <summary>
        /// Shows the request status. Returns true for success and false for failure.
        /// </summary>
        [JsonProperty("success")]
        public bool? Success { get; set; }

        /// <summary>
        /// Contains the view count details.
        /// </summary>
        [JsonProperty("data")]
        public ViewsCountResponseData? Data { get; set; }
    }
}