//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Contains the view count details.
    /// </summary>
    public class ViewsCountResponseData
    {

        /// <summary>
        /// Number of views for the stream or resource.
        /// </summary>
        [JsonProperty("views")]
        public long? Views { get; set; }
    }
}