/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Components
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Type of overlay (currently only supports &quot;watermark&quot;).
    /// </summary>
    public enum WatermarkInputType
    {
        [JsonProperty("watermark")]
        Watermark,
    }

    public static class WatermarkInputTypeExtension
    {
        public static string Value(this WatermarkInputType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static WatermarkInputType ToEnum(this string value)
        {
            foreach(var field in typeof(WatermarkInputType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is WatermarkInputType)
                    {
                        return (WatermarkInputType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum WatermarkInputType");
        }
    }

}