/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */

#nullable enable
namespace Fastpix.Models.Errors
{
    using System;
    using System.Net.Http;

    public class ApiException : FastpixException
    {
        /// <summary>
        /// Default API exception.
        /// </summary>
        public ApiException(
            string message,
            HttpRequestMessage request,
            HttpResponseMessage response,
            string body
        ): base(message, request, response, body) {}
    }
}
