/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Utils
{
    /// <summary>
    /// SDK constants for version information and language identification.
    /// </summary>
    public static class Constants
    {
        /// <summary>
        /// The language identifier for this SDK.
        /// </summary>
        public const string Language = "csharp";

        /// <summary>
        /// The version of the SDK.
        /// </summary>
        public const string SdkVersion = "1.1.0";

        /// <summary>
        /// The version of the SDK generator used to create this SDK.
        /// </summary>
        public const string SdkGenVersion = "2.788.7";

        /// <summary>
        /// The version of the OpenAPI document used to generate this SDK.
        /// </summary>
        public const string OpenApiDocVersion = "1.0.0";
    }
}

