//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class AddMediaTrackRequestBody
    {

        /// <summary>
        /// Contains details about the track being added to the media file.
        /// </summary>
        [JsonProperty("tracks")]
        public AddTrackRequest? Tracks { get; set; }
    }
}