/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class AddMediaTrackRequestBody
    {

        /// <summary>
        /// Contains details about the track being added to the media file.
        /// </summary>
        [JsonProperty("tracks")]
        public AddTrackRequest Tracks { get; set; } = default!;
    }
}