//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    
    public class CreateMediaPlaybackIdRequest
    {

        /// <summary>
        /// When creating the media, FastPix assigns a universally unique identifier with a maximum length of 255 characters.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=mediaId")]
        public string MediaId { get; set; } = default!;

        /// <summary>
        /// Request body for creating playback id for an media
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=application/json")]
        public CreateMediaPlaybackIdRequestBody? RequestBody { get; set; }
    }
}