//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class DeleteMediaPlaybackIdRequest
    {

        /// <summary>
        /// Return the universal unique identifier for media which can contain a maximum of 255 characters.
        /// </summary>
        [SpeakeasyMetadata("pathParam:style=simple,explode=false,name=mediaId")]
        public string MediaId { get; set; } = default!;

        /// <summary>
        /// Return the universal unique identifier for playbacks  which can contain a maximum of 255 characters. 
        /// </summary>
        [SpeakeasyMetadata("queryParam:style=form,explode=true,name=playbackId")]
        public string PlaybackId { get; set; } = default!;
    }
}