/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class DeleteMediaPlaybackIdRequest
    {

        /// <summary>
        /// The unique identifier assigned to the media when created. The value must be a valid UUID.
        /// </summary>
        [FastpixMetadata("pathParam:style=simple,explode=false,name=mediaId")]
        public string MediaId { get; set; } = default!;

        /// <summary>
        /// Return the universal unique identifier for playbacks  which can contain a maximum of 255 characters. 
        /// </summary>
        [FastpixMetadata("queryParam:style=form,explode=true,name=playbackId")]
        public string PlaybackId { get; set; } = default!;
    }
}