/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class GetAllPlaylistsRequest
    {

        /// <summary>
        /// The number of playlists to return (default is 10, max is 50).
        /// </summary>
        [FastpixMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 10;

        /// <summary>
        /// The page number to retrieve, starting from 1. Use this parameter to paginate the playlist results.
        /// </summary>
        [FastpixMetadata("queryParam:style=form,explode=true,name=offset")]
        public long? Offset { get; set; } = 1;
    }
}