/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class GetDrmConfigurationByIdRequest
    {

        /// <summary>
        /// The unique identifier of the DRM configuration.
        /// </summary>
        [FastpixMetadata("pathParam:style=simple,explode=false,name=drmConfigurationId")]
        public string DrmConfigurationId { get; set; } = default!;
    }
}