//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class GetDrmConfigurationRequest
    {

        /// <summary>
        /// Offset determines the starting point for data retrieval within a paginated list.
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=offset")]
        public long? Offset { get; set; } = 1;

        /// <summary>
        /// Limit specifies the maximum number of items to display per page.
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 10;
    }
}