//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    public class GetDataViewlistCurrentViewsFilterData
    {

        /// <summary>
        /// Number of concurrent viewers for this dimension value.
        /// </summary>
        [JsonProperty("concurrent_viewers")]
        public long? ConcurrentViewers { get; set; }

        /// <summary>
        /// Name of the dimension (e.g., country, device type, etc.).
        /// </summary>
        [JsonProperty("dimension_name")]
        public string? DimensionName { get; set; }

        /// <summary>
        /// Additional metric value for this dimension (if applicable).
        /// </summary>
        [JsonProperty("metricValue")]
        public long? MetricValue { get; set; }
    }
}