/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class GetPlaybackIdDomains
    {

        [JsonProperty("defaultPolicy")]
        public GetPlaybackIdDomainsDefaultPolicy? DefaultPolicy { get; set; }

        [JsonProperty("allow")]
        public List<string>? Allow { get; set; }

        [JsonProperty("deny")]
        public List<string>? Deny { get; set; }
    }
}