/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class GetPlaylistByIdRequest
    {

        /// <summary>
        /// The unique id of the playlist you want to retrieve.
        /// </summary>
        [FastpixMetadata("pathParam:style=simple,explode=false,name=playlistId")]
        public string PlaylistId { get; set; } = default!;
    }
}