/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Restrictions applied to this playback ID.
    /// </summary>
    public class GetPlaybackIdAccessRestrictions
    {

        [JsonProperty("domains")]
        public GetPlaybackIdDomains? Domains { get; set; }

        [JsonProperty("userAgents")]
        public GetPlaybackIdUserAgents? UserAgents { get; set; }
    }
}