//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class GetSigningKeyByIdRequest
    {

        /// <summary>
        /// When creating the signing key, FastPix assigns a universally unique identifier with a maximum length of 255 characters. 
        /// </summary>
        [FastPixMetadata("pathParam:style=simple,explode=false,name=signingKeyId")]
        public string SigningKeyId { get; set; } = default!;
    }
}