//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class GetVideoViewDetailsRequest
    {

        /// <summary>
        /// Pass View id
        /// </summary>
        [FastPixMetadata("pathParam:style=simple,explode=false,name=viewId")]
        public string ViewId { get; set; } = default!;
    }
}