/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    
    public class GetVideoViewDetailsRequest
    {

        /// <summary>
        /// Pass View Id
        /// </summary>
        [FastpixMetadata("pathParam:style=simple,explode=false,name=viewId")]
        public string ViewId { get; set; } = default!;
    }
}