//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Displays the result of the request.
    /// </summary>
    public class ListErrorsData
    {

        /// <summary>
        /// Retrieves a list of errors that have occurred in the system.
        /// </summary>
        [JsonProperty("errors")]
        public List<ErrorDetails>? Errors { get; set; }

        /// <summary>
        /// Retrieves a list of errors that have occurred most frequently in the system, ranked by their count of occurrences.
        /// </summary>
        [JsonProperty("topErrors")]
        public List<TopErrorDetails>? TopErrors { get; set; }
    }
}