/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Get the list of Views
    /// </summary>
    public class ListDimensionsResponseBody
    {

        /// <summary>
        /// Shows the request status. Returns true for success and false for failure.
        /// </summary>
        [JsonProperty("success")]
        public bool? Success { get; set; }

        /// <summary>
        /// The endpoint retrieves a comprehensive list of dimensions
        /// </summary>
        [JsonProperty("data")]
        public List<string>? Data { get; set; }
    }
}