//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Components;
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    
    public class ListVideoViewsRequest
    {

        /// <summary>
        /// This parameter specifies the time span between which the video views list should be retrieved by. You can provide either from and to unix epoch timestamps or time duration. The scope of duration is between 60 minutes to 30 days.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=timespan[]")]
        public ListVideoViewsTimespan Timespan { get; set; } = default!;

        /// <summary>
        /// Pass the dimensions and their corresponding values you want to filter the views by. For excluding the values in the filter we can pass &apos;!&apos; before the filter value. The list of filters can be obtained from list of dimensions endpoint.<br/>
        /// 
        /// <remarks>
        /// Example Values : [ browser_name:Chrome , os_name:macOS , device_name:Galaxy ]<br/>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=filterby[]")]
        public string? Filterby { get; set; }

        /// <summary>
        /// Pass the limit to display only the rows specified by the value.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=limit")]
        public long? Limit { get; set; } = 10;

        /// <summary>
        /// Pass the offset value to indicate the page number.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=offset")]
        public long? Offset { get; set; } = 1;

        /// <summary>
        /// Pass the viewer_id to filter the list of views. This value can be manually set during integration or generated by FastPix. When set manually it can be a string of aplha numeric values of any length.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=viewerId")]
        public string? ViewerId { get; set; }

        /// <summary>
        /// Pass the error code to filter the list of views. The possible values of error code can be fetched from list of errors end point.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=errorCode")]
        public ErrorCode? ErrorCode { get; set; } = null;

        /// <summary>
        /// Pass this value to sort the view list by.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=orderBy")]
        public string? OrderBy { get; set; } = "view_end";

        /// <summary>
        /// The order direction to sort the view list by.<br/>
        /// 
        /// <remarks>
        /// 
        /// </remarks>
        /// </summary>
        [FastPixMetadata("queryParam:style=form,explode=true,name=sortOrder")]
        public string? SortOrder { get; set; } = "asc";
    }
}