/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Requests;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Get video media input information
    /// </summary>
    public class RetrieveMediaInputInfoResponseBody
    {

        /// <summary>
        /// Shows the request status. Returns true for success and false for failure.
        /// </summary>
        [JsonProperty("success")]
        public bool? Success { get; set; }

        /// <summary>
        /// Displays the result of the request.
        /// </summary>
        [JsonProperty("data")]
        public RetrieveMediaInputInfoData? Data { get; set; }
    }
}