/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    using System.Numerics;
    using System.Reflection;

    public class TrackType
    {
        private TrackType(string value) { Value = value; }

        public string Value { get; private set; }

        public static TrackType VideoTrack { get { return new TrackType("VideoTrack"); } }

        public static TrackType AudioTrack { get { return new TrackType("AudioTrack"); } }

        public static TrackType SubtitleTrack { get { return new TrackType("SubtitleTrack"); } }

        public override string ToString() { return Value; }
        public static implicit operator String(TrackType v) { return v.Value; }
        public static TrackType FromString(string v) {
            switch(v) {
                case "VideoTrack": return VideoTrack;
                case "AudioTrack": return AudioTrack;
                case "SubtitleTrack": return SubtitleTrack;
                default: throw new ArgumentException("Invalid value for TrackType");
            }
        }
        public override bool Equals(object? obj)
        {
            if (obj == null || GetType() != obj.GetType())
            {
                return false;
            }
            return Value.Equals(((TrackType)obj).Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }
    }


    [JsonConverter(typeof(Track.TrackConverter))]
    public class Track
    {
        public Track(TrackType type)
        {
            Type = type;
        }

        [FastpixMetadata("form:explode=true")]
        public VideoTrack? VideoTrack { get; set; }

        [FastpixMetadata("form:explode=true")]
        public AudioTrack? AudioTrack { get; set; }

        [FastpixMetadata("form:explode=true")]
        public SubtitleTrack? SubtitleTrack { get; set; }

        public TrackType Type { get; set; }
        public static Track CreateVideoTrack(VideoTrack videoTrack)
        {
            TrackType typ = TrackType.VideoTrack;

            Track res = new Track(typ);
            res.VideoTrack = videoTrack;
            return res;
        }
        public static Track CreateAudioTrack(AudioTrack audioTrack)
        {
            TrackType typ = TrackType.AudioTrack;

            Track res = new Track(typ);
            res.AudioTrack = audioTrack;
            return res;
        }
        public static Track CreateSubtitleTrack(SubtitleTrack subtitleTrack)
        {
            TrackType typ = TrackType.SubtitleTrack;

            Track res = new Track(typ);
            res.SubtitleTrack = subtitleTrack;
            return res;
        }

        public class TrackConverter : JsonConverter
        {
            public override bool CanConvert(System.Type objectType) => objectType == typeof(Track);

            public override bool CanRead => true;

            public override object? ReadJson(JsonReader reader, System.Type objectType, object? existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null)
                {
                    throw new InvalidOperationException("Received unexpected null JSON value");
                }

                var json = JRaw.Create(reader).ToString();
                var fallbackCandidates = new List<(System.Type, object, string)>();

                try
                {
                    return new Track(TrackType.AudioTrack)
                    {
                        AudioTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<AudioTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(AudioTrack), new Track(TrackType.AudioTrack), "AudioTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Track(TrackType.SubtitleTrack)
                    {
                        SubtitleTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<SubtitleTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(SubtitleTrack), new Track(TrackType.SubtitleTrack), "SubtitleTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                try
                {
                    return new Track(TrackType.VideoTrack)
                    {
                        VideoTrack = ResponseBodyDeserializer.DeserializeUndiscriminatedUnionMember<VideoTrack>(json)
                    };
                }
                catch (ResponseBodyDeserializer.MissingMemberException)
                {
                    fallbackCandidates.Add((typeof(VideoTrack), new Track(TrackType.VideoTrack), "VideoTrack"));
                }
                catch (ResponseBodyDeserializer.DeserializationException)
                {
                    // try next option
                }
                catch (Exception)
                {
                    throw;
                }

                if (fallbackCandidates.Count > 0)
                {
                    fallbackCandidates.Sort((a, b) => ResponseBodyDeserializer.CompareFallbackCandidates(a.Item1, b.Item1, json));
                    foreach(var (deserializationType, returnObject, propertyName) in fallbackCandidates)
                    {
                        try
                        {
                            return ResponseBodyDeserializer.DeserializeUndiscriminatedUnionFallback(deserializationType, returnObject, propertyName, json);
                        }
                        catch (ResponseBodyDeserializer.DeserializationException)
                        {
                            // try next fallback option
                        }
                        catch (Exception)
                        {
                            throw;
                        }
                    }
                }

                throw new InvalidOperationException("Could not deserialize into any supported types.");
            }

            public override void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer)
            {
                if (value == null)
                {
                    throw new InvalidOperationException("Unexpected null JSON value.");
                }

                Track res = (Track)value;

                if (res.VideoTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.VideoTrack));
                    return;
                }

                if (res.AudioTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.AudioTrack));
                    return;
                }

                if (res.SubtitleTrack != null)
                {
                    writer.WriteRawValue(Utilities.SerializeJSON(res.SubtitleTrack));
                    return;
                }
            }

        }

    }
}