//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by FastPix (https://FastPix.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    public class UpdatedMediaRequestBody
    {

        [JsonProperty("metadata")]
        public Dictionary<string, string>? Metadata { get; set; }
    }
}