/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Media details updated successfully with the named entity extraction feature enabled or disabled
    /// </summary>
    public class UpdateMediaNamedEntitiesResponseBody
    {

        /// <summary>
        /// Indicates if the request was successful or not.
        /// </summary>
        [JsonProperty("success")]
        public bool? Success { get; set; }

        [JsonProperty("data")]
        public NamedEntitiesResponse? Data { get; set; }
    }
}