/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Models.Components;
    using Fastpix.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Media details updated successfully
    /// </summary>
    public class UpdatedMediaResponseBody
    {

        /// <summary>
        /// Demonstrates whether the request is successful or not.
        /// </summary>
        [JsonProperty("success")]
        public bool? Success { get; set; }

        [JsonProperty("data")]
        public UpdateMedia? Data { get; set; }
    }
}