/* 
 * This file is auto-generated.
 * Do not edit this file manually.
 * Your changes will be overwritten during the next generation.
 */
#nullable enable
namespace Fastpix.Models.Requests
{
    using Fastpix.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// Specify the fallback behavior for domains that are not listed in the `allow` or `deny` lists.
    /// </summary>
    public enum UpdateLiveStreamDomainRestrictionsDefaultPolicy
    {
        [JsonProperty("allow")]
        Allow,
        [JsonProperty("deny")]
        Deny,
    }

    public static class UpdateLiveStreamDomainRestrictionsDefaultPolicyExtension
    {
        public static string Value(this UpdateLiveStreamDomainRestrictionsDefaultPolicy value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static UpdateLiveStreamDomainRestrictionsDefaultPolicy ToEnum(this string value)
        {
            foreach(var field in typeof(UpdateLiveStreamDomainRestrictionsDefaultPolicy).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is UpdateLiveStreamDomainRestrictionsDefaultPolicy updateLiveStreamDomainRestrictionsDefaultPolicy)
                    {
                        return updateLiveStreamDomainRestrictionsDefaultPolicy;
                    }
                }
            }

            throw new ArgumentException($"Unknown value {value} for enum UpdateLiveStreamDomainRestrictionsDefaultPolicy", nameof(value));
        }
    }

}